language: cpp
compiler: 
  - gcc
#  - clang
sudo: required
dist: trusty
      
install:
  # CppCheck
  - sudo apt-get install -qq cppcheck

script:
  # We need to increase tolerance for TravisCI since there are unpredictable effects.
  - make TOLERANCE=100 "COVERAGE_FLAGS=-fprofile-arcs -ftest-coverage" COVERAGE_LIBS=-lgcov
  # CppCheck
  - make cppcheck || cat cppcheck-report.xml
  # Tests
  - make test
  # Gcov
  - cd src/ && gcov -r  knarr.cpp && cd ..

after_success:
    # codecov.io
    - bash <(curl -s https://codecov.io/bash) -X gcov -f src/knarr.cpp.gcov

notifications:
  email:
    recipients:
      - d.desensi.software@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
  
