language: cpp
compiler:
  - gcc
#  - clang
sudo: required
dist: trusty

install:
  # Cmake
  - sudo apt-get install cmake
  # CppCheck
  - sudo apt-get install -qq cppcheck
  # Gcovr
  - sudo apt-get install python-pip
  - pip install requests[security]
  - pip install --user gcovr

script:
  # Runs compilation, cppcheck, tests and coverage collection
  - mkdir build
  - cd build
  - cmake ../ -DENABLE_CODECOV=ON -DENABLE_TESTS=ON -DENABLE_CPPCHECK=ON
  - make && make cppcheck # && make coverage 
  - cd ..

after_success:
  # codecov.io
  - bash <(curl -s https://codecov.io/bash) -f build/coverage.xml

notifications:
  email:
    recipients:
      - d.desensi.software@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

